In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("messy_employee_dataset.csv")

In [3]:
print(df.shape)
df.head(10)

(1555, 10)

,Employee_ID,Full_Name,Gender,Age,Department,Salary,Join_Date,City,Phone_Number,Performance_Score
0,EMP0001,Mariam Hussain,Female,47,Sales,32051,22-10-2018,Peshawar,03183206688,Excellent
1,EMP0002,Javed Kiani,Male,55,IT,188017,2018-12-10,Lahore,03285210503,11
2,EMP0003,Muhammad Qureshi,Male,56,HR,224851,2013-02-23,Rawalpindi,03363538936,NaN
3,EMP0004,Sadia Malik,Female,44,Marketing,232817,2013-11-17,Peshawer,003334132613,62
4,EMP0005,Usman Javed,male,43,Marketing,146862,NaN,Lahore,03356958354,82
5,EMP0006,Naveed Siddiqui,Male,55,Sales,90277,2012-03-14,Multan,03411502307,46
6,EMP0007,ayesha jafri,Female,56,IT,NaN,01/09/2022,Rawalpindi,0306-153-0317,30
7,EMP0008,Rukhsar Javed,Female,52,Marketing,98771,2012-09-26,karachi,03053078648,67
8,EMP0009,Rukhsar Butt,Male,NaN,Finance,205120,2012-10-15,Peshawar,03314177925,95
9,EMP0010,Nadia Aziz,Female,49,Sales,121634,2016-08-06,Quetta,0341-903-8057,58

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1555 non-null   object
 1   Full_Name          1545 non-null   object
 2   Gender             1545 non-null   object
 3   Age                1459 non-null   object
 4   Department         1474 non-null   object
 5   Salary             1471 non-null   object
 6   Join_Date          1457 non-null   object
 7   City               1484 non-null   object
 8   Phone_Number       1453 non-null   object
 9   Performance_Score  1488 non-null   object
dtypes: object(10)
memory usage: 121.6+ KB

In [5]:
# to count complete empty rows
df.isnull().all(axis=1).sum()

np.int64(0)

In [6]:
# to count complete empty columns
df.isnull().all().sum()  # you can use isna
# df.isna().all().sum()

np.int64(0)

In [7]:
df.describe(include='all') # to information of all columns

,Employee_ID,Full_Name,Gender,Age,Department,Salary,Join_Date,City,Phone_Number,Performance_Score
count,1555,1545,1545,1459,1474,1471,1457,1484,1453,1488
unique,1555,1041,10,52,32,1355,1207,45,1383,113
top,EMP0001,Imran Zaidi,Female,49,Operations,5000000,TBD,Islamabad,Not Given,11
freq,1,6,674,50,227,14,16,148,20,23

In [8]:
# lets show the unique entries in each column
df.nunique()

Employee_ID          1555
Full_Name            1041
Gender                 10
Age                    52
Department             32
Salary               1355
Join_Date            1207
City                   45
Phone_Number         1383
Performance_Score     113
dtype: int64

In [9]:
df.isna().sum()

Employee_ID            0
Full_Name             10
Gender                10
Age                   96
Department            81
Salary                84
Join_Date             98
City                  71
Phone_Number         102
Performance_Score     67
dtype: int64

In [10]:
df['Gender'].unique()

array(['Female', 'Male', 'male ', 'M', 'male', 'female', 'F', 'FEMALE',
       nan, 'MALE', 'female '], dtype=object)

In [11]:
df['Gender']=df["Gender"].str.strip().str.lower()

In [12]:
#making maping
gender_map={'f':'female','m':'male'}
# apply mapping
df['Gender']=df['Gender'].replace(gender_map)

In [13]:
df['Gender'].unique()

array(['female', 'male', nan], dtype=object)

In [14]:
# fill null values with mode
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
# lets make it capitalize
df["Gender"]=df["Gender"].str.capitalize()
#lets count unique values now
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [15]:
# lets see the string data in age column
strings_in_age=df['Age'].apply(lambda x: isinstance(x,str))
strings_in_age

0       True
1       True
2       True
3       True
4       True
        ...
1550    True
1551    True
1552    True
1553    True
1554    True
Name: Age, Length: 1555, dtype: bool

In [16]:
# to know the alphabitic rows only
invalid_ages = df[pd.to_numeric(df['Age'], errors='coerce').isna()]

print(invalid_ages[['Age']])

         Age
8        NaN
27    thirty
39       NaN
62       NaN
71       NaN
...      ...
1469     NaN
1481  thirty
1489     NaN
1518     NaN
1529     NaN

[154 rows x 1 columns]

In [17]:
# to identify
invalid_values = df.loc[
    pd.to_numeric(df['Age'], errors='coerce').isna(),
    'Age'
]

print(invalid_values.unique())

[nan 'thirty' 'forty' 'twenty-five']

In [18]:
# this is equivelent to 
mask = pd.to_numeric(df['Age'], errors='coerce').isna()
invalied_values1=df.loc[mask, 'Age']
invalied_values1.unique()

array([nan, 'thirty', 'forty', 'twenty-five'], dtype=object)

In [19]:
age_map={'thirty':30,'forty':40,'twenty-five':25}
df['Age']=df['Age'].replace(age_map)

In [20]:
df['Age']=pd.to_numeric(df['Age'])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1555 non-null   object
 1   Full_Name          1545 non-null   object
 2   Gender             1555 non-null   object
 3   Age                1459 non-null   float64
 4   Department         1474 non-null   object
 5   Salary             1471 non-null   object
 6   Join_Date          1457 non-null   object
 7   City               1484 non-null   object
 8   Phone_Number       1453 non-null   object
 9   Performance_Score  1488 non-null   object
dtypes: float64(1), object(9)
memory usage: 121.6+ KB

In [22]:
df.columns=df.columns.str.strip().str.lower()

In [23]:
df.columns

Index(['employee_id', 'full_name', 'gender', 'age', 'department', 'salary',
       'join_date', 'city', 'phone_number', 'performance_score'],
      dtype='object')

In [24]:
df['city']=df['city'].str.lower().str.strip()
df['city'].unique()

array(['peshawar', 'lahore', 'rawalpindi', 'peshawer', 'multan',
       'karachi', 'quetta', 'faisalabad', 'sialkot', 'gujranwala',
       'islamabad', nan, 'queta', 'rawalpind', 'isb', 'islambad', 'lhr',
       'multn', 'qta', 'lahor', 'pesh', 'rwp', 'mltn'], dtype=object)

In [25]:
# lets order these cities alphabitically
unique_cities = sorted(df['city'].dropna().unique())

print(unique_cities)

['faisalabad', 'gujranwala', 'isb', 'islamabad', 'islambad', 'karachi', 'lahor', 'lahore', 'lhr', 'mltn', 'multan', 'multn', 'pesh', 'peshawar', 'peshawer', 'qta', 'queta', 'quetta', 'rawalpind', 'rawalpindi', 'rwp', 'sialkot']

In [26]:
city_map={'islambad':'islamabad','isb':'islamabad','lahor':'lahore','lhr':'lahore','multn':'multan',
         'pesh':'peshawar','peshawer':'peshawar','qta':'quetta','queta':'queta','rawalpind':'rawalpindi',
         'rwp':'rawalpindi'
         }
df['city']=df['city'].replace(city_map)
df['city'].unique()

array(['peshawar', 'lahore', 'rawalpindi', 'multan', 'karachi', 'quetta',
       'faisalabad', 'sialkot', 'gujranwala', 'islamabad', nan, 'queta',
       'mltn'], dtype=object)

In [27]:
df['city']=df['city'].fillna(df['city'].mode()[0])
df['city'].unique()

array(['peshawar', 'lahore', 'rawalpindi', 'multan', 'karachi', 'quetta',
       'faisalabad', 'sialkot', 'gujranwala', 'islamabad', 'queta',
       'mltn'], dtype=object)

In [28]:
df['department']=df['department'].str.lower().str.strip()
df['department'].unique()

array(['sales', 'it', 'hr', 'marketing', 'finance', 'sale', 'operations',
       nan, 'h.r', 'i.t', 'i.t.', 'mktg', 'ops', 'fin', 'h.r.', 'op'],
      dtype=object)

In [29]:
department_unique=sorted(df['department'].dropna().unique())

In [30]:
print(department_unique)

['fin', 'finance', 'h.r', 'h.r.', 'hr', 'i.t', 'i.t.', 'it', 'marketing', 'mktg', 'op', 'operations', 'ops', 'sale', 'sales']

In [31]:
dept_map={'fin':'finance','h.r':'hr','h.r.':'hr','i.t':'it','i.t.':'it','mktg':'marketing',
          'op':'operations','ops':'operations','sale':'sales'}
df['department']=df['department'].replace(dept_map)
df['department'].unique()

array(['sales', 'it', 'hr', 'marketing', 'finance', 'operations', nan],
      dtype=object)

In [32]:
df['department']=df['department'].fillna(df['department'].mode()[0])
df['department']
df['department'].unique()

array(['sales', 'it', 'hr', 'marketing', 'finance', 'operations'],
      dtype=object)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        1555 non-null   object
 1   full_name          1545 non-null   object
 2   gender             1555 non-null   object
 3   age                1459 non-null   float64
 4   department         1555 non-null   object
 5   salary             1471 non-null   object
 6   join_date          1457 non-null   object
 7   city               1555 non-null   object
 8   phone_number       1453 non-null   object
 9   performance_score  1488 non-null   object
dtypes: float64(1), object(9)
memory usage: 121.6+ KB

In [34]:
df['salary']=df['salary'].str.lower().str.strip()

In [35]:
# to show only text
text_values = df.loc[df['salary'].str.contains(r'[A-Za-z]', regex=True, na=False), 'salary'].unique().tolist()

print(text_values)

['rs. 159589', 'rs. 128311', 'one lakh', 'fifty thousand', 'rs. 188651', 'rs. 144923', 'rs. 45915', 'rs. 150568', 'rs. 139674', 'rs. 186500', 'rs. 54724', 'rs. 34444', 'rs. 103224', 'rs. 132422', 'rs. 49252', 'rs. 88451', 'rs. 62221', 'rs. 93878', 'rs. 165778', 'rs. 48928', 'rs. 87182', 'rs. 70689', 'rs. 39357', 'rs. 66789', 'rs. 119561', 'rs. 194233', 'rs. 81467', 'rs. 129863', 'rs. 197592', 'rs. 163610', 'rs. 115599', 'rs. 144266', 'rs. 147681', 'rs. 170140', 'rs. 60900', 'rs. 72466', 'rs. 157581', 'rs. 39546', 'rs. 63928', 'rs. 199859', 'rs. 97683', 'rs. 175697', 'rs. 58062', 'rs. 78683', 'rs. 46745', 'rs. 50278', 'rs. 188855', 'rs. 168919', 'rs. 125868', 'rs. 134879']

In [36]:
df['salary'] = df['salary'].replace(['N/A', 'NA', 'n/a', 'na'], np.nan)

In [37]:
word_map = {
    'one lakh': 100000, 
    'fifty thousand': 50000
}

# Map text values to numbers (lowercasing strings for safe matching)
df['salary'] = df['salary'].replace(word_map)

In [38]:
# Convert to string so we can use .str accessor methods
df['salary'] = df['salary'].astype(str)

In [39]:
df['salary'] = (
    df['salary']
    .str.replace('Rs.', '', regex=False)
    .str.replace('Rs', '', regex=False)
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.rstrip('-') # Removes trailing dashes like '167043-'
    .str.strip()     # Removes leftover spaces
)

In [40]:
df['salary'] = df['salary'].replace('nan', np.nan)

In [41]:
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')

# View the result
df['salary'].head()

0     32051.0
1    188017.0
2    224851.0
3    232817.0
4    146862.0
Name: salary, dtype: float64

In [42]:
df['salary']=df['salary'].fillna(df['salary'].mean())

In [43]:
df.isnull().sum()

employee_id            0
full_name             10
gender                 0
age                   96
department             0
salary                 0
join_date             98
city                   0
phone_number         102
performance_score     67
dtype: int64

In [44]:
# Step 1: Attempt to convert Join_Date to datetime, turning invalid text into NaT
parsed_dates = pd.to_datetime(df['join_date'], errors='coerce')

C:\Users\Masaud.0495812\AppData\Local\Temp\ipykernel_19616\682895301.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  parsed_dates = pd.to_datetime(df['join_date'], errors='coerce')

In [45]:
# Step 2: Create a mask where the original value is not null, but the parsed date is null (meaning it's text/invalid)
text_entries_mask = df['join_date'].notna() & parsed_dates.isna()

In [46]:
# Step 3: Extract and view the unique text or invalid entries found in the column
unique_text_values = df.loc[text_entries_mask, 'join_date'].unique()

In [47]:
print("Non-date text entries found:")
print(unique_text_values)

Non-date text entries found:
['2018-12-10' '2013-02-23' '2013-11-17' ... '2021-02-11' '2012-01-05'
 '2020-04-19']

In [48]:
# Clean the column: converts valid dates to standard format, turns text/invalid into NaT
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce', format='mixed')

# Verify the changes
print(df['join_date'].head())
print(f"Total missing dates (NaT): {df['join_date'].isna().sum()}")

0   2018-10-22
1   2018-12-10
2   2013-02-23
3   2013-11-17
4          NaT
Name: join_date, dtype: datetime64[ns]
Total missing dates (NaT): 171

In [49]:
# Apply backward fill to the Join_Date column
df['join_date'] = df['join_date'].bfill()

# Verify that all missing values have been filled
print("Null values after backward fill:", df['join_date'].isna().sum())

Null values after backward fill: 0

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        1555 non-null   object
 1   full_name          1545 non-null   object
 2   gender             1555 non-null   object
 3   age                1459 non-null   float64
 4   department         1555 non-null   object
 5   salary             1555 non-null   float64
 6   join_date          1555 non-null   datetime64[ns]
 7   city               1555 non-null   object
 8   phone_number       1453 non-null   object
 9   performance_score  1488 non-null   object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 121.6+ KB

In [51]:
# Convert the column to strings so we can manipulate the text safely
df['phone_number'] = df['phone_number'].astype(str)

# Step 1: Replace any text entries (like "Not Given" or "nan") with actual missing values
df.loc[df['phone_number'].str.contains(r'[a-zA-Z]', na=False), 'phone_number'] = np.nan

# Step 2: Remove anything that isn't a digit (like +, -, spaces)
df['phone_number'] = df['phone_number'].str.replace(r'\D', '', regex=True)

# Step 3: Replace numbers starting with '92' or '00' so they start with a standard '0'
df['phone_number'] = df['phone_number'].str.replace(r'^92', '0', regex=True)
df['phone_number'] = df['phone_number'].str.replace(r'^00', '0', regex=True)

# Step 4: Check length and keep only the ones that are exactly 11 digits long
valid_length_mask = df['phone_number'].str.len() == 11
df['phone_number'] = df['phone_number'].where(valid_length_mask, np.nan)

# Verify the clean results and check for missing values
print(df['phone_number'].head(10))
print(f"\nTotal missing or invalid numbers: {df['phone_number'].isna().sum()}")

0    03183206688
1    03285210503
2    03363538936
3    03334132613
4    03356958354
5    03411502307
6    03061530317
7    03053078648
8    03314177925
9    03419038057
Name: phone_number, dtype: object

Total missing or invalid numbers: 135

In [52]:
df.head()

,employee_id,full_name,gender,age,department,salary,join_date,city,phone_number,performance_score
0,EMP0001,Mariam Hussain,Female,47.0,sales,32051.0,2018-10-22,peshawar,03183206688,Excellent
1,EMP0002,Javed Kiani,Male,55.0,it,188017.0,2018-12-10,lahore,03285210503,11
2,EMP0003,Muhammad Qureshi,Male,56.0,hr,224851.0,2013-02-23,rawalpindi,03363538936,NaN
3,EMP0004,Sadia Malik,Female,44.0,marketing,232817.0,2013-11-17,peshawar,03334132613,62
4,EMP0005,Usman Javed,Male,43.0,marketing,146862.0,2012-03-14,lahore,03356958354,82

In [53]:
df.head()

,employee_id,full_name,gender,age,department,salary,join_date,city,phone_number,performance_score
0,EMP0001,Mariam Hussain,Female,47.0,sales,32051.0,2018-10-22,peshawar,03183206688,Excellent
1,EMP0002,Javed Kiani,Male,55.0,it,188017.0,2018-12-10,lahore,03285210503,11
2,EMP0003,Muhammad Qureshi,Male,56.0,hr,224851.0,2013-02-23,rawalpindi,03363538936,NaN
3,EMP0004,Sadia Malik,Female,44.0,marketing,232817.0,2013-11-17,peshawar,03334132613,62
4,EMP0005,Usman Javed,Male,43.0,marketing,146862.0,2012-03-14,lahore,03356958354,82

In [54]:
# Spaces remove karein
df['performance_score'] = df['performance_score'].astype('string').str.strip()

# Check karein kaun-si values directly numeric nahi hain
numeric_check = pd.to_numeric(
    df['performance_score'],
    errors='coerce'
)

text_values = df.loc[
    numeric_check.isna() & df['performance_score'].notna(),
    'performance_score'
].unique()

print("Categorical/Text values:")
print(text_values)

Categorical/Text values:
<StringArray>
['Excellent', 'Good', 'Poor', 'Average']
Length: 4, dtype: string

In [55]:
# the above can also be done as


# Create a mask for alphabetical characters, ignoring 'NaN'
text_mask = df['performance_score'].astype(str).str.contains(r'[a-zA-Z]', na=False)
text_mask = text_mask & (df['performance_score'].astype(str).str.lower() != 'nan')

# Print the extracted text values
print(df.loc[text_mask, 'performance_score'].value_counts())

performance_score
Excellent    13
Poor         12
Average      11
Good         10
Name: count, dtype: Int64

In [56]:
# Define what numeric score each text value should represent
score_mapping = {
    'Excellent': 95,
    'Good': 75,
    'Average': 50,
    'Poor': 25
}

In [57]:
# Replace the text strings in the column with their new numeric values
df['performance_score'] = df['performance_score'].replace(score_mapping)

In [58]:
# Check the results to confirm the text has been successfully swapped for numbers
text_mask = df['performance_score'].astype(str).str.contains(r'[a-zA-Z]', na=False)
text_mask = text_mask & (df['performance_score'].astype(str).str.lower() != 'nan')

print("Text values remaining after mapping:")
print(df.loc[text_mask, 'performance_score'].value_counts())

Text values remaining after mapping:
Series([], Name: count, dtype: int64)

In [59]:
df['performance_score']=pd.to_numeric(df['performance_score'])

In [60]:
df.head()

,employee_id,full_name,gender,age,department,salary,join_date,city,phone_number,performance_score
0,EMP0001,Mariam Hussain,Female,47.0,sales,32051.0,2018-10-22,peshawar,03183206688,95.0
1,EMP0002,Javed Kiani,Male,55.0,it,188017.0,2018-12-10,lahore,03285210503,11.0
2,EMP0003,Muhammad Qureshi,Male,56.0,hr,224851.0,2013-02-23,rawalpindi,03363538936,NaN
3,EMP0004,Sadia Malik,Female,44.0,marketing,232817.0,2013-11-17,peshawar,03334132613,62.0
4,EMP0005,Usman Javed,Male,43.0,marketing,146862.0,2012-03-14,lahore,03356958354,82.0

In [61]:
df.isnull().sum()

employee_id            0
full_name             10
gender                 0
age                   96
department             0
salary                 0
join_date              0
city                   0
phone_number         135
performance_score     67
dtype: int64

In [62]:
df['full_name']=df['full_name'].replace(np.nan,'unknown')

In [63]:
df['phone_number']=df['phone_number'].replace(np.nan,'unknown')

In [64]:
df['age']=df['age'].replace(np.nan,'unknown')

In [65]:
df['performance_score']=df['performance_score'].replace(np.nan,'unknown')

In [66]:
# Save the cleaned dataframe to a new CSV file
df.to_csv('cleaned_employee_dataset.csv', index=False)

print("Data saved successfully as 'cleaned_employee_dataset.csv'!")

Data saved successfully as 'cleaned_employee_dataset.csv'!